/** Common DAF dropdown options (India govt exam context). */

export const DEGREE_OPTIONS = [
  "BA",
  "BSc",
  "BCom",
  "BBA",
  "BTech / BE",
  "MBBS",
  "LLB",
  "MA",
  "MSc",
  "MCom",
  "MBA",
  "MTech / ME",
  "PhD",
  "Other",
] as const;

export const INSTITUTION_OPTIONS = [
  "IIT Delhi",
  "IIT Bombay",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Roorkee",
  "NIT Trichy",
  "NIT Warangal",
  "NIT Surathkal",
  "Delhi University",
  "Jawaharlal Nehru University (JNU)",
  "University of Hyderabad",
  "Banaras Hindu University (BHU)",
  "University of Mumbai",
  "University of Calcutta",
  "University of Madras",
  "Anna University",
  "Jamia Millia Islamia",
  "Aligarh Muslim University (AMU)",
  "BITS Pilani",
  "IISc Bangalore",
  "AIIMS Delhi",
  "NLSIU Bangalore",
  "Other",
] as const;

export const OPTIONAL_SUBJECT_OPTIONS = [
  "Not applicable",
  "History",
  "Geography",
  "Political Science & International Relations",
  "Sociology",
  "Public Administration",
  "Anthropology",
  "Philosophy",
  "Psychology",
  "Economics",
  "Law",
  "Literature (English)",
  "Literature (Hindi)",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Agriculture",
  "Medical Science",
  "Other",
] as const;

export const ENGINEERING_BRANCH_OPTIONS = [
  "Not applicable",
  "Mechanical",
  "Electrical",
  "Electronics & Communication",
  "Civil",
  "Computer Science",
  "Chemical",
  "Instrumentation",
  "Production / Industrial",
  "Other",
] as const;

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Jammu & Kashmir",
  "Ladakh",
  "Other",
] as const;
