/** Hard prompts that force ~10 minutes of genuine research before a short speech. */

export const DEEP_RESEARCH_TOPICS = [
  "Compare how three different countries legally define 'hate speech' online — and what trade-offs each regime accepts",
  "Trace the full supply chain of a smartphone battery from mine to landfill and where accountability actually fails",
  "Why did the 2008 financial crisis transmission mechanisms differ between the US, Iceland, and India?",
  "Map the science and politics of solar geoengineering: who decides if it is ever used?",
  "Explain how CRISPR clinical trials get approved differently in the US, EU, and China — with one real case study",
  "Reconstruct the collapse of a major dam or bridge in the last 20 years: engineering failure vs governance failure",
  "How do refugee status determination procedures actually work at the UNHCR versus one national asylum system?",
  "Quantify and explain urban heat-island interventions that worked vs failed in two megacities",
  "Dissect one Investor–State Dispute Settlement (ISDS) case and its implications for climate regulation",
  "Compare Central Bank Digital Currency designs in three jurisdictions: privacy, programmability, and financial stability",
  "Why do some post-conflict truth commissions succeed as public memory projects while others deepen polarization?",
  "Audit the evidence behind '15-minute cities' — what is solid urban science vs conspiratorial distortion?",
  "Explain antibiotic resistance as an economic externality: incentives of pharma, hospitals, and livestock industries",
  "How does semiconductor export control policy reshape alliances in the Indo-Pacific? Use at least two primary documents",
  "Model the water–energy–food nexus conflict in one river basin that crosses borders",
  "What actually changed in workplace surveillance law after a landmark data-protection ruling? Pick one region",
  "Compare land rights for indigenous communities under ILO 169 versus a domestic statute — where courts matter",
  "Reconstruct how a misinformation narrative about vaccines or elections propagated across platforms for 72 hours",
  "Evaluate whether 'green hydrogen' projects in one country are industrial strategy or stranded-asset risk",
  "Explain how algorithmic credit scoring creates disparate impact — with methods used in one empirical study",
  "Why did one high-speed rail megaproject succeed while a peer project stalled? Budget, land, politics",
  "Trace how rare-earth refining concentration creates geopolitical leverage — and what diversification costs",
  "Dissect a failed public–private partnership hospital or airport and who bore residual risk",
  "How do war-crimes investigations gather digital evidence admissibly? Constraints on OSINT",
  "Compare career technical education models in Germany, Singapore, and one developing economy — transferability limits",
  "Explain oceanic plastic credits / offset markets: measurement problems and greenwashing pathways",
  "What does 'strategic autonomy' mean operationally for defense procurement in Europe vs India?",
  "Audit maternal mortality interventions that closed caste/race gaps — effect sizes and why replication fails",
  "How did one country's coal transition package handle workers — numbers, timelines, political bargains",
  "Reconstruct a major cyber incident on critical infrastructure and the disclosure dilemmas regulators faced",
  "Compare cryptocurrency taxation regimes and enforcement capacity in three jurisdictions",
  "Why do some agricultural MSP-style policies stabilize incomes while others create permanent fiscal traps?",
  "Explain deep-seabed mining governance under UNCLOS — who can legally mine what, and environmental unknowns",
  "Map how university rankings shape migration of students and faculty — incentives and perverse outcomes",
  "Dissect one climate litigation win against a government or company: legal theory and real-world follow-through",
  "How do export controls and dual-use rules apply to AI model weights versus chips?",
  "Compare restorative justice programs and their measured effects on reoffending in two countries",
  "Explain the thermodynamic and economic limits of recycling lithium-ion batteries at scale",
  "What caused a specific currency crisis in the last 40 years — capital flows, policy errors, and politics",
  "How do pandemic origin debates illustrate standards of scientific evidence versus geopolitical narrative?",
  "Evaluate congestion pricing in one city with before/after mobility and equity data",
  "Trace how a traditional ecological knowledge claim entered (or failed to enter) a formal conservation plan",
  "Compare age-verification mandates for social media: constitutional tests and technical feasibility",
  "Explain ballistic missile defense effectiveness claims versus published intercept statistics",
  "How does informal work get counted — or erased — in national accounts of one developing economy?",
  "Dissect a failed AI deployment in public welfare or policing: failure mode taxonomy",
  "What would a rigorous evaluation of 'universal basic income' pilots actually require methodologically?",
  "Compare heritage restitution cases for museum artifacts — legal routes and diplomatic side-effects",
  "Explain methane attribution science for oil/gas vs agriculture and why policy treats them differently",
  "How do sanctions evade through third-country trade? Reconstruct one sanctioned commodity chain",
  "Evaluate open-source intelligence ethics when documenting atrocities — consent, safety, verification",
  "Why do some housing first policies reduce chronic homelessness while others face political backlash?",
  "Map the patent landscape around mRNA platforms and implications for pandemic preparedness equity",
  "Compare federal versus unitary responses to disaster relief — fiscal federalism under climate stress",
  "Explain orbital debris mitigation rules and why a Kessler syndrome scenario is hard to govern",
];

export const DEEP_RESEARCH_FRAMES = [
  (core: string) => core,
  (core: string) =>
    `${core} — You must cite at least two concrete mechanisms (legal, scientific, or economic), not slogans.`,
  (core: string) =>
    `${core} Dedicate research time to finding a counterexample that weakens the popular narrative.`,
  (core: string) =>
    `${core} Focus on measurement: what data would convince a skeptical examiner?`,
  (core: string) =>
    `${core} Compare across continents — avoid single-country tunnel vision.`,
];
