import type { Category } from "./fields";

export type ExamKind =
  | "civil-services"
  | "language"
  | "mba-wat-gd"
  | "law"
  | "interview"
  | "debate"
  | "scholarship"
  | "english-honours"
  | "essay-heavy";

export type Exam = {
  id: string;
  name: string;
  shortName: string;
  aliases: string[];
  country: string;
  region: string;
  continent: string;
  kind: ExamKind;
  fields: Exclude<Category, "all">[];
  /** Clean speaking / extempore / interview themes (shown as-is or lightly shaped) */
  themes: string[];
  /** Authentic-style essay titles/prompts for this exam family */
  essayTopics: string[];
};

const UPSC_ESSAYS = [
  "The time to repair the roof is when the sun is shining",
  "Forests precede civilizations and deserts follow them",
  "A society that has more justice is a society that needs less charity",
  "Technology as the silent factor in international relations",
  "Mindful manifesto is the catalyst to a tranquil self",
  "History is a series of victories won by the scientific man over the romantic man",
  "Your perception of me is a reflection of you; my reaction to you is an awareness of me",
  "Poets are the unacknowledged legislators of the world",
  "Hand that rocks the cradle rules the world",
  "What is research, but a blind date with knowledge",
  "There are better practices to life than finding escape in dreams",
  "Rise of Artificial Intelligence: the threat of jobless future or better job opportunities through reskilling",
  "Social media is inherently a selfish medium",
  "Neglect of primary healthcare and education in India is creating a society of unequal",
  "Biased media is a real threat to Indian democracy",
  "Values are not what humanity is, but what humanity ought to be",
  "Courage to accept and dedication to improve are two keys to success",
  "South Asian societies are woven not around the state, but around their plural cultures and plural identities",
  "Best for an individual is not necessarily best for the society",
  "Has the Non-Alignment Movement (NAM) lost its relevance in a multipolar world?",
  "Farming has lost the ability to be a source of subsistence for majority of farmers in India",
  "Impact of the new economic measures on fiscal ties between the union and states in India",
  "Destiny of a nation is shaped in its classrooms",
  "Near jobless growth in India: An anomaly or an outcome of economic reforms",
  "Water disputes between states of India",
  "Cooperative federalism: Myth or reality",
  "Digital economy: A leveler or a source of economic inequality",
  "Innovation is the key determinant of economic growth and social welfare",
  "Management of Indian border disputes – a complex task",
  "Fulfillment of new woman in India is a myth",
  "We may brave human laws but cannot resist natural laws",
  "Need brings greed, if greed increases it spoils breed",
  "If development is not engendered, it is endangered",
  "Lending hands to someone is better than giving a dole",
  "Quick but steady wins the race",
  "Character of an institution is reflected in its leader",
  "Education without values, as useful as it is, seems rather to make a man a more clever devil",
  "Is the growing level of competition good for the youth?",
  "Are the standardized tests good measure of academic ability or progress?",
  "Words are sharper than the two-edged sword",
  "Is sting operation an invasion of privacy?",
  "Was it the policy paralysis or the paralysis of implementation which slowed the growth of our country?",
  "Tourism: Can this be the next big thing for India?",
  "Crisis of ethical values in modern business",
  "Does Indian cinema shape our popular culture or merely reflect it",
  "Is the criticism that the Indian judiciary is too slow and ineffective justified?",
  "Globalization versus nationalism",
  "Science and Mysticism: Are they compatible?",
  "There is nothing either good or bad, but thinking makes it so",
  "You cannot step twice in the same river",
  "Be the change you want to see in others",
  "With greater power comes greater responsibility",
  "Ships do not sink because of water around them; ships sink because of water that gets into them",
  "Simplicity is the ultimate sophistication",
  "The process of self-discovery has now been technologically outsourced",
  "Life is long journey between human being and being humane",
  "Mind without fear is a reckless mind",
  "A ship in harbour is safe, but that is not what ship is for",
  "The enduring relevance of soft power in a hard world",
  "Climate justice is incomplete without gender justice",
  "Poverty anywhere is a threat to prosperity everywhere",
  "Culture is what we are, civilization is what we have",
  "There can be no social justice without economic justice",
  "Artificial Intelligence will not replace humans; humans with AI will",
  "Violence is the last refuge of the incompetent",
  "The road from spoken word to viral outrage",
  "Constitutional morality versus popular morality",
  "Growth that is not inclusive is growth that will not last",
  "Silence of good people is worse than the noise of bad actors",
  "Nationalism without compassion becomes exclusion",
];

const UPSC_SPEAK = [
  "cooperative federalism",
  "judicial activism",
  "electoral reforms",
  "freebies versus welfare",
  "climate adaptation finance",
  "women in workforce",
  "police reforms",
  "data protection",
  "MSP debates",
  "urban flooding",
  "secularism in practice",
  "AI in public administration",
  "border management",
  "universal basic services",
  "ethical governance",
  "media trials",
  "demographic dividend",
  "river rejuvenation",
  "startup India realities",
  "tribal rights",
  "cryptocurrency regulation",
  "soft power of India",
  "gig worker protections",
  "education outcomes vs enrolment",
  "one nation one election",
  "lateral entry into civil services",
  "simultaneous elections",
  "parliamentary disruption",
  "NITI Aayog relevance",
  "GST and federal bargaining",
  "uniform civil code debates",
  "agri marketing reforms",
  "water stress in cities",
  "mission KarmaYogi",
  "official language policy",
  "india's neighbourhood first",
  "strategic autonomy",
  "space as soft power",
  "healthcare primary focus",
  "malnutrition paradox",
];

const IELTS_ESSAYS = [
  "Some people believe that unpaid community service should be a compulsory part of high school programmes. To what extent do you agree or disagree?",
  "In many countries, the amount of crime is increasing. What do you think are the main causes of crime? How can we deal with those causes?",
  "Some people think that parents should teach children how to be good members of society. Others believe that school is the place to learn this. Discuss both views and give your opinion.",
  "Nowadays many people choose to be self-employed, rather than to work for a company or organisation. Why might this be the case? What could be the disadvantages of being self-employed?",
  "Some people say that the best way to improve public health is by increasing the number of sports facilities. Others, however, say that this would have little effect and other measures are required. Discuss both views.",
  "In some countries, more and more people are becoming interested in finding out about the history of the house or building they live in. What are the reasons for this? How can people research this?",
  "Many manufactured food and drink products contain high levels of sugar, which causes many health problems. Sugary products should be made more expensive to encourage people to consume less sugar. Do you agree or disagree?",
  "Some people think that all university students should study whatever they like. Others believe they should only be allowed to study subjects that will be useful in the future, such as those related to science and technology. Discuss both views.",
  "In the age of digital communication, handwritten letters and face-to-face conversations are becoming less common. Is this a positive or negative development?",
  "Governments should spend money on railways rather than roads. To what extent do you agree or disagree?",
  "Some people believe that it is best to accept a bad situation, such as an unsatisfactory job or shortage of money. Others argue that it is better to try and improve such situations. Discuss both views.",
  "Nowadays the way many people interact with each other has changed because of technology. In what ways has technology affected the types of relationships people make? Has this become a positive or negative development?",
  "Some experts believe that it is better for children to begin learning a foreign language at primary school rather than secondary school. Do the advantages outweigh the disadvantages?",
  "In many countries, plastic shopping bags are still widely used. What problems does this cause, and what solutions can you suggest?",
  "Some people think that a sense of competition in children should be encouraged. Others believe that children who are taught to co-operate rather than compete become more useful adults. Discuss both views.",
];

const IELTS_SPEAK = [
  "a skill you want to learn",
  "your favourite public place",
  "an advertisement you remember",
  "a time you helped someone",
  "a traditional festival",
  "online learning",
  "traffic in cities",
  "reading habits",
  "healthy food choices",
  "famous people and privacy",
  "working from home",
  "protecting old buildings",
  "team sports versus individual sports",
  "learning history",
  "shopping habits",
  "noise pollution",
  "museums",
  "public transport",
  "childhood games",
  "climate and daily life",
];

const MBA_ESSAYS = [
  "Profit is not a purpose; it is a result",
  "Ethics and competitiveness can coexist",
  "Is hustle culture burning out a generation?",
  "The founder is not always the best CEO",
  "Customer is not always right — discuss",
  "Diversity without inclusion is decoration",
  "Can AI make managers fairer, or only faster?",
  "Layoffs reveal company culture more than mission statements",
  "Is remote work the future or a pandemic exception?",
  "Greenwashing is the new corporate sin",
  "Should India prefer unicorns or profitable SMEs?",
  "Fail fast is a luxury not everyone can afford",
  "MBA degrees: signal or skill?",
  "Stakeholder capitalism is easier said than measured",
  "Are employee surveillance tools a necessary evil?",
  "Price wars destroy industries faster than they build market share",
  "Social media has turned brands into publishers — for better or worse",
  "Crisis is the real interview of leadership",
  "Is 'move fast and break things' ethical in fintech?",
  "Globalization is being replaced by friendshoring — discuss",
];

const MBA_SPEAK = [
  "four-day work week",
  "founder mode",
  "gig economy dignity",
  "platform monopolies",
  "ESG reporting honesty",
  "internship as free labour",
  "brand activism risks",
  "women in leadership pipelines",
  "India's consumption story",
  "cash burn culture",
  "work-from-anywhere visas",
  "AI replacing junior analysts",
  "customer data ethics",
  "family business succession",
  "India vs China manufacturing",
];

const GRE_ESSAYS = [
  "Educational institutions have a responsibility to dissuade students from pursuing fields of study in which they are unlikely to succeed.",
  "Governments should focus on solving the immediate problems of today rather than on trying to solve the anticipated problems of the future.",
  "Scandals are useful because they focus our attention on problems in ways that no speaker or reformer ever could.",
  "In any field of endeavor, it is impossible to make a significant contribution without first being strongly influenced by past achievements within that field.",
  "Nations should suspend government funding for the arts when significant numbers of their citizens are hungry or unemployed.",
  "People's behavior is largely determined by forces not of their own making.",
  "Leaders are created by the demands that are placed on them.",
  "The surest indicator of a great nation is represented not by the achievements of its rulers, artists, or scientists, but by the general welfare of its people.",
  "The best ideas arise from a passionate interest in commonplace things.",
  "As we acquire more knowledge, things do not become more comprehensible, but more complex and mysterious.",
];

const CSS_ESSAYS = [
  "Imagination is more important than knowledge",
  "Not all that glitters is gold",
  "The hierarchy of needs is the hierarchy of culture",
  "Globalization and electronic media — meaning of prosperity",
  "Truth is a rare commodity despite the freedom by the print and electronic media",
  "Of all forms of injustice, injustice to the young and vulnerable is the worst",
  "Governance crisis in Pakistan — need for reforms",
  "Gender equality is a myth",
  "Education, health and poverty — the sacred triangle",
  "Democracy without free media is incomplete",
  "Climate change: a human security challenge for South Asia",
  "Can meaning be fixed? Language as a site of power",
  "Prosperous countries make peaceful neighbours",
  "Radicalization: causes and remedies",
  "Human development is the real development",
];

const OXBRIDGE = [
  "Should prisoners have the right to vote?",
  "Is forgiveness a public duty?",
  "Can a machine understand a poem?",
  "Do animals have rights, or do humans have duties?",
  "Is inequality always unfair?",
  "What makes a law legitimate?",
  "Is beauty a social construct?",
  "Should universities teach employability or truth?",
  "Is silence a form of speech?",
  "Do countries have a moral right to control borders?",
];

const COLLEGE_ENGLISH = [
  "Literature is news that stays news",
  "Can translation ever be faithful?",
  "The unreliable narrator and modern politics",
  "Memes as contemporary folklore",
  "Why read poetry in an age of timelines?",
  "Censorship begins with taste — discuss",
  "The campus novel as social critique",
  "Is authorship dead in the age of AI writing tools?",
  "Dialects deserve the same respect as standard language",
  "Tragedy is more truthful than comedy — agree or disagree",
];

const SCHOLARSHIP = [
  "Leadership is service under pressure",
  "How will you multiply this opportunity for others?",
  "Local problems, global tools",
  "Integrity when no one is watching",
  "Bridging communities that do not usually meet",
  "Failure that taught you policy",
  "Why your country needs your subject now",
  "Climate and inequality are one story",
  "Public narrative versus private motive",
  "The ethics of ambition",
];

const DEBATE_MOTIONS = [
  "This House would ban unpaid internships",
  "This House believes cancel culture strengthens accountability",
  "This House would prioritise climate adaptation over net-zero deadlines in the Global South",
  "This House regrets the rise of influencer philanthropy",
  "This House would allow prisoners to vote",
  "This House believes AI-generated art should be copyrightable",
  "This House would break up Big Tech",
  "This House supports a universal basic income",
  "This House would make voting compulsory",
  "This House believes universities should decolonise their curricula",
];

function exam(e: Exam): Exam {
  return {
    ...e,
    themes: [...new Set(e.themes)],
    essayTopics: [...new Set(e.essayTopics)],
  };
}

/** Exams / admissions that actually need speaking, WAT, GD, interview, or essay writing. */
export const EXAMS: Exam[] = [
  exam({
    id: "upsc-cse",
    name: "UPSC Civil Services (CSE) — Essay & Personality Test",
    shortName: "UPSC",
    aliases: ["upsc", "ias", "ips", "cse", "civil services"],
    country: "India",
    region: "India",
    continent: "Asia",
    kind: "civil-services",
    fields: ["governance", "ethics", "current-affairs", "domestic", "international", "economy"],
    themes: UPSC_SPEAK,
    essayTopics: UPSC_ESSAYS,
  }),
  exam({
    id: "state-psc",
    name: "State PSC / PCS — Essay & Interview",
    shortName: "State PSC",
    aliases: ["pcs", "state psc", "mpsc", "uppsc", "bpsc"],
    country: "India",
    region: "Indian states",
    continent: "Asia",
    kind: "civil-services",
    fields: ["governance", "domestic", "current-affairs", "economy"],
    themes: [
      ...UPSC_SPEAK.slice(0, 25),
      "district administration",
      "panchayati raj",
      "state finance commission",
      "local language in governance",
      "regional aspirations",
    ],
    essayTopics: [
      ...UPSC_ESSAYS.slice(0, 40),
      "Strong states make a strong nation",
      "Local self-government is the soul of democracy",
      "Regional development cannot wait for the centre",
      "Bureaucracy at the grassroots",
    ],
  }),
  exam({
    id: "css-pakistan",
    name: "Pakistan CSS — Essay & Viva",
    shortName: "CSS",
    aliases: ["css", "pakistan css"],
    country: "Pakistan",
    region: "Pakistan",
    continent: "Asia",
    kind: "essay-heavy",
    fields: ["governance", "international", "ethics", "current-affairs"],
    themes: UPSC_SPEAK.slice(0, 30),
    essayTopics: CSS_ESSAYS,
  }),
  exam({
    id: "bcs",
    name: "Bangladesh BCS — Written & Viva",
    shortName: "BCS",
    aliases: ["bcs", "bangladesh civil"],
    country: "Bangladesh",
    region: "Bangladesh",
    continent: "Asia",
    kind: "civil-services",
    fields: ["governance", "domestic", "current-affairs"],
    themes: UPSC_SPEAK.slice(0, 28),
    essayTopics: [
      ...CSS_ESSAYS.slice(0, 8),
      "Development with equity",
      "Riverine nation, climate destiny",
      "Women's empowerment as national strategy",
      "Education as liberation",
    ],
  }),
  exam({
    id: "bank-po",
    name: "IBPS / SBI PO — GD & Interview",
    shortName: "Bank PO",
    aliases: ["ibps", "sbi po", "bank po"],
    country: "India",
    region: "India",
    continent: "Asia",
    kind: "mba-wat-gd",
    fields: ["finance", "economy", "current-affairs", "ethics"],
    themes: [
      "financial inclusion",
      "digital payments security",
      "NPAs and moral hazard",
      "cryptocurrency for banks",
      "customer data privacy",
      "green finance",
      "rural banking trust",
      "fintech partnership risks",
      "women's banking access",
      "cashless economy myths",
    ],
    essayTopics: [
      "Financial inclusion without financial literacy is incomplete",
      "Digital India and the unbanked",
      "Ethics in lending",
      "Can banks be both profitable and social?",
      "Cashless is not paperless trust",
    ],
  }),
  exam({
    id: "rbi-grade-b",
    name: "RBI Grade B — Descriptive & Interview",
    shortName: "RBI Grade B",
    aliases: ["rbi", "grade b"],
    country: "India",
    region: "India",
    continent: "Asia",
    kind: "essay-heavy",
    fields: ["finance", "economy", "governance", "international"],
    themes: [
      "inflation targeting",
      "central bank independence",
      "financial stability",
      "CBDC privacy",
      "rupee internationalisation",
      "climate risk in banking",
      "payment systems resilience",
    ],
    essayTopics: [
      "Price stability is a public good",
      "Central bank communication as policy",
      "Fintech regulation: innovation versus integrity",
      "Inclusive growth needs patient capital",
      "Global shocks, local policy space",
    ],
  }),
  exam({
    id: "cat-wat-gd",
    name: "CAT / IIM — WAT, GD & PI",
    shortName: "CAT/IIM",
    aliases: ["cat", "iim", "wat", "gd pi"],
    country: "India",
    region: "India",
    continent: "Asia",
    kind: "mba-wat-gd",
    fields: ["business", "economy", "ethics", "current-affairs"],
    themes: MBA_SPEAK,
    essayTopics: MBA_ESSAYS,
  }),
  exam({
    id: "xat",
    name: "XAT — Essay & Interview",
    shortName: "XAT",
    aliases: ["xat", "xlri"],
    country: "India",
    region: "India",
    continent: "Asia",
    kind: "mba-wat-gd",
    fields: ["business", "ethics", "abstract"],
    themes: [...MBA_SPEAK, "ethical ambiguity at work", "decision making under incomplete data"],
    essayTopics: [
      ...MBA_ESSAYS,
      "Ethical dilemmas have no perfect answers — only accountable ones",
      "Kindness is a strategic advantage",
    ],
  }),
  exam({
    id: "snap-nmat",
    name: "SNAP / NMAT — GD-PI tracks",
    shortName: "SNAP/NMAT",
    aliases: ["snap", "nmat", "symbiosis", "nmims"],
    country: "India",
    region: "India",
    continent: "Asia",
    kind: "mba-wat-gd",
    fields: ["business", "current-affairs"],
    themes: MBA_SPEAK,
    essayTopics: MBA_ESSAYS.slice(0, 12),
  }),
  exam({
    id: "campus-gd",
    name: "Campus placements — GD / Extempore / HR",
    shortName: "Campus GD",
    aliases: ["gd", "extempore", "campus placement", "group discussion"],
    country: "India",
    region: "India",
    continent: "Asia",
    kind: "mba-wat-gd",
    fields: ["current-affairs", "business", "ethics", "technology-ai"],
    themes: [
      ...MBA_SPEAK,
      "India at 2047",
      "brain drain",
      "social media trials",
      "college rankings obsession",
      "internship quality",
    ],
    essayTopics: MBA_ESSAYS.slice(0, 15),
  }),
  exam({
    id: "clat",
    name: "CLAT / NLUs — English & Interview",
    shortName: "CLAT",
    aliases: ["clat", "nlu", "ailet", "law entrance"],
    country: "India",
    region: "India",
    continent: "Asia",
    kind: "law",
    fields: ["law-justice", "ethics", "current-affairs", "governance"],
    themes: [
      "free speech limits",
      "bail reform",
      "privacy rights",
      "media trials",
      "judicial delays",
      "uniform civil code",
      "sedition debates",
      "legal aid access",
    ],
    essayTopics: [
      "Justice delayed is justice denied — still true?",
      "Privacy in a surveillance age",
      "Law without ethics is machinery",
      "Public interest litigation: remedy or overload?",
      "Free speech and hurt sentiments",
    ],
  }),
  exam({
    id: "ielts",
    name: "IELTS — Speaking & Writing",
    shortName: "IELTS",
    aliases: ["ielts"],
    country: "Global",
    region: "Global",
    continent: "Global",
    kind: "language",
    fields: ["education", "society-culture", "environment", "health", "technology-ai"],
    themes: IELTS_SPEAK,
    essayTopics: IELTS_ESSAYS,
  }),
  exam({
    id: "toefl",
    name: "TOEFL — Speaking & Writing",
    shortName: "TOEFL",
    aliases: ["toefl"],
    country: "USA-oriented",
    region: "United States",
    continent: "North America",
    kind: "language",
    fields: ["education", "science-tech", "society-culture"],
    themes: IELTS_SPEAK,
    essayTopics: IELTS_ESSAYS,
  }),
  exam({
    id: "pte",
    name: "PTE Academic — Speaking & Writing",
    shortName: "PTE",
    aliases: ["pte"],
    country: "Global",
    region: "Global",
    continent: "Global",
    kind: "language",
    fields: ["education", "society-culture", "business"],
    themes: IELTS_SPEAK,
    essayTopics: IELTS_ESSAYS.slice(0, 10),
  }),
  exam({
    id: "duolingo",
    name: "Duolingo English Test",
    shortName: "DET",
    aliases: ["duolingo", "det"],
    country: "Global",
    region: "Global",
    continent: "Global",
    kind: "language",
    fields: ["education", "society-culture", "technology-ai"],
    themes: IELTS_SPEAK,
    essayTopics: IELTS_ESSAYS.slice(0, 8),
  }),
  exam({
    id: "cambridge-english",
    name: "Cambridge C1 Advanced / C2 Proficiency",
    shortName: "Cambridge English",
    aliases: ["cae", "cpe", "cambridge english", "c1", "c2"],
    country: "Global",
    region: "Global",
    continent: "Global",
    kind: "language",
    fields: ["education", "society-culture", "abstract", "media"],
    themes: IELTS_SPEAK,
    essayTopics: [
      ...IELTS_ESSAYS.slice(0, 8),
      "Advertising shapes desire more than it informs choice",
      "Is progress always improvement?",
      "Public figures have no right to privacy",
    ],
  }),
  exam({
    id: "gre-awa",
    name: "GRE — Analytical Writing",
    shortName: "GRE AWA",
    aliases: ["gre", "awa", "issue essay"],
    country: "USA-oriented",
    region: "United States",
    continent: "North America",
    kind: "essay-heavy",
    fields: ["abstract", "education", "ethics", "governance"],
    themes: [
      "expertise versus democracy",
      "progress and complexity",
      "arts funding",
      "standardized testing",
      "scientific consensus",
    ],
    essayTopics: GRE_ESSAYS,
  }),
  exam({
    id: "gmat-mba",
    name: "GMAT / global MBA interviews",
    shortName: "GMAT/MBA",
    aliases: ["gmat", "mba interview"],
    country: "Global",
    region: "Global",
    continent: "Global",
    kind: "mba-wat-gd",
    fields: ["business", "ethics", "international"],
    themes: MBA_SPEAK,
    essayTopics: MBA_ESSAYS,
  }),
  exam({
    id: "oxbridge",
    name: "Oxbridge / elite UK interviews",
    shortName: "Oxbridge",
    aliases: ["oxbridge", "oxford", "cambridge interview"],
    country: "United Kingdom",
    region: "United Kingdom",
    continent: "Europe",
    kind: "interview",
    fields: ["abstract", "ethics", "law-justice", "society-culture"],
    themes: [
      "meaning of fairness",
      "limits of free speech",
      "what counts as evidence",
      "national borders ethics",
      "beauty and truth",
    ],
    essayTopics: OXBRIDGE,
  }),
  exam({
    id: "ib-tok",
    name: "IB Theory of Knowledge / EE defence",
    shortName: "IB TOK",
    aliases: ["ib", "tok", "extended essay"],
    country: "Global",
    region: "Global",
    continent: "Global",
    kind: "essay-heavy",
    fields: ["abstract", "ethics", "education", "science-tech"],
    themes: [
      "knowledge and belief",
      "bias in expertise",
      "emotion as a way of knowing",
      "language shaping thought",
      "certainty in science",
    ],
    essayTopics: [
      "To what extent do we need evidence to know?",
      "Does language determine what we can know?",
      "Are some types of knowledge more useful than others?",
      "How do biases affect the production of knowledge?",
      "Can art be a form of knowledge?",
    ],
  }),
  exam({
    id: "a-level-epq",
    name: "A-Levels / EPQ viva",
    shortName: "A-Level/EPQ",
    aliases: ["a level", "epq", "a-levels"],
    country: "United Kingdom",
    region: "United Kingdom",
    continent: "Europe",
    kind: "essay-heavy",
    fields: ["education", "abstract", "society-culture"],
    themes: IELTS_SPEAK.slice(0, 12),
    essayTopics: [
      ...OXBRIDGE.slice(0, 6),
      "Should school league tables be abolished?",
      "Is offline childhood a human right?",
    ],
  }),
  exam({
    id: "english-honours",
    name: "English Honours / Literature admissions",
    shortName: "English Hons",
    aliases: ["english honours", "literature", "ba english", "english major"],
    country: "Global",
    region: "Global",
    continent: "Global",
    kind: "english-honours",
    fields: ["society-culture", "abstract", "media", "ethics"],
    themes: [
      "reading in the age of reels",
      "canon versus syllabus",
      "adaptation fidelity",
      "writer's responsibility",
      "regional literature visibility",
    ],
    essayTopics: COLLEGE_ENGLISH,
  }),
  exam({
    id: "du-jnu-ba",
    name: "DU / JNU / Indian BA interviews",
    shortName: "DU/JNU",
    aliases: ["delhi university", "jnu", "ba interview", "cuet interview"],
    country: "India",
    region: "India",
    continent: "Asia",
    kind: "interview",
    fields: ["society-culture", "current-affairs", "education", "abstract"],
    themes: [
      "why this subject",
      "campus politics and learning",
      "reading beyond syllabus",
      "freedom of expression on campus",
      "reservation and merit debates",
    ],
    essayTopics: [
      ...COLLEGE_ENGLISH.slice(0, 6),
      "Universities should disturb the comfortable",
      "Critical thinking cannot be multiple-choice",
    ],
  }),
  exam({
    id: "uk-fast-stream",
    name: "UK Civil Service Fast Stream",
    shortName: "UK Fast Stream",
    aliases: ["fast stream", "uk civil service"],
    country: "United Kingdom",
    region: "United Kingdom",
    continent: "Europe",
    kind: "interview",
    fields: ["governance", "ethics", "domestic", "international"],
    themes: [
      "evidence-based policy",
      "public service impartiality",
      "digital government trust",
      "regional inequality UK",
      "ethical AI in welfare",
    ],
    essayTopics: [
      "Impartiality in a polarised age",
      "Delivery matters more than announcement",
      "Who should decide what count as public value?",
    ],
  }),
  exam({
    id: "fsot",
    name: "US Foreign Service (FSOT / Oral)",
    shortName: "FSOT",
    aliases: ["fsot", "foreign service", "fsoa"],
    country: "United States",
    region: "United States",
    continent: "North America",
    kind: "interview",
    fields: ["international", "ethics", "security-defence", "current-affairs"],
    themes: [
      "public diplomacy",
      "consular crisis judgment",
      "trade and values",
      "alliance management",
      "soft power limits",
    ],
    essayTopics: [
      "Diplomacy is the art of letting someone else have your way",
      "National interest and human rights — can they align?",
      "Information wars and democratic resilience",
    ],
  }),
  exam({
    id: "epso",
    name: "EPSO / EU Concours",
    shortName: "EPSO",
    aliases: ["epso", "eu concours"],
    country: "European Union",
    region: "the European Union",
    continent: "Europe",
    kind: "interview",
    fields: ["international", "governance", "law-justice", "economy"],
    themes: [
      "subsidiarity",
      "EU enlargement",
      "rule of law in the union",
      "green deal trade-offs",
      "multilingual public service",
    ],
    essayTopics: [
      "Unity in diversity is a policy, not a slogan",
      "Can a common market sustain a common democracy?",
    ],
  }),
  exam({
    id: "singapore-psc",
    name: "Singapore PSC scholarships / interviews",
    shortName: "Singapore PSC",
    aliases: ["singapore psc", "psc scholarship"],
    country: "Singapore",
    region: "Singapore",
    continent: "Asia",
    kind: "scholarship",
    fields: ["governance", "ethics", "international", "economy"],
    themes: [
      "meritocracy critiques",
      "small state strategy",
      "social cohesion policy",
      "public housing dignity",
    ],
    essayTopics: SCHOLARSHIP,
  }),
  exam({
    id: "chevening",
    name: "Chevening interviews",
    shortName: "Chevening",
    aliases: ["chevening"],
    country: "United Kingdom",
    region: "United Kingdom",
    continent: "Europe",
    kind: "scholarship",
    fields: ["international", "governance", "education", "ethics"],
    themes: [
      "networking as public good",
      "leadership in your sector",
      "UK study impact at home",
    ],
    essayTopics: SCHOLARSHIP,
  }),
  exam({
    id: "fulbright",
    name: "Fulbright interviews",
    shortName: "Fulbright",
    aliases: ["fulbright"],
    country: "United States",
    region: "United States",
    continent: "North America",
    kind: "scholarship",
    fields: ["international", "education", "society-culture", "ethics"],
    themes: [
      "cultural exchange value",
      "research that travels",
      "bridge-building stories",
    ],
    essayTopics: SCHOLARSHIP,
  }),
  exam({
    id: "rhodes-scholarship",
    name: "Rhodes / major scholarship interviews",
    shortName: "Rhodes+",
    aliases: ["rhodes", "scholarship interview", "gates cambridge"],
    country: "Global",
    region: "Global",
    continent: "Global",
    kind: "scholarship",
    fields: ["ethics", "international", "education", "abstract"],
    themes: [
      "fight the world's fight",
      "character under scrutiny",
      "ambition with humility",
    ],
    essayTopics: SCHOLARSHIP,
  }),
  exam({
    id: "un-ypp",
    name: "UN YPP / UN interviews",
    shortName: "UN YPP",
    aliases: ["un ypp", "united nations interview"],
    country: "Global",
    region: "the United Nations system",
    continent: "Global",
    kind: "interview",
    fields: ["international", "ethics", "governance", "current-affairs"],
    themes: [
      "SDG localisation",
      "humanitarian access dilemmas",
      "multilingual multilateralism",
      "peacekeeping legitimacy",
    ],
    essayTopics: [
      "We the peoples — still a credible phrase?",
      "Development without dignity is not development",
      "Neutrality and justice in humanitarian work",
    ],
  }),
  exam({
    id: "toastmasters",
    name: "Toastmasters / Table Topics",
    shortName: "Toastmasters",
    aliases: ["toastmasters", "table topics"],
    country: "Global",
    region: "Global",
    continent: "Global",
    kind: "debate",
    fields: ["abstract", "society-culture", "business", "ethics"],
    themes: [
      "courage",
      "listening",
      "first impressions",
      "failure",
      "gratitude",
      "deadlines",
      "mentorship",
      "habits",
    ],
    essayTopics: [
      "The speech you needed years ago",
      "Confidence is a practice, not a personality",
    ],
  }),
  exam({
    id: "wudc",
    name: "WUDC / British Parliamentary Debate",
    shortName: "WUDC/BP",
    aliases: ["wudc", "british parliamentary", "debate"],
    country: "Global",
    region: "Global",
    continent: "Global",
    kind: "debate",
    fields: ["international", "ethics", "governance", "economy"],
    themes: DEBATE_MOTIONS.map((m) => m.replace(/^This House (would |believes |regrets |supports )?/i, "")),
    essayTopics: DEBATE_MOTIONS,
  }),
  exam({
    id: "mun",
    name: "Model UN",
    shortName: "MUN",
    aliases: ["mun", "model united nations"],
    country: "Global",
    region: "Global",
    continent: "Global",
    kind: "debate",
    fields: ["international", "security-defence", "environment", "current-affairs"],
    themes: [
      "Security Council reform",
      "climate finance",
      "refugee burden sharing",
      "cyber norms",
      "humanitarian corridors",
    ],
    essayTopics: [
      "Sovereignty and responsibility to protect",
      "Are sanctions a moral instrument?",
      "Youth participation in diplomacy",
    ],
  }),
  exam({
    id: "tedx",
    name: "TEDx / keynote audition",
    shortName: "TEDx",
    aliases: ["tedx", "ted talk"],
    country: "Global",
    region: "Global",
    continent: "Global",
    kind: "debate",
    fields: ["abstract", "science-tech", "society-culture", "ethics"],
    themes: [
      "an idea worth spreading from your life",
      "a belief you changed",
      "a local problem with a simple fix",
    ],
    essayTopics: [
      "Ideas do not spread themselves",
      "Vulnerability as leadership",
    ],
  }),
  exam({
    id: "ifs-mea",
    name: "IFS / MEA interview practice",
    shortName: "IFS",
    aliases: ["ifs", "mea", "indian foreign service"],
    country: "India",
    region: "India",
    continent: "Asia",
    kind: "interview",
    fields: ["international", "security-defence", "current-affairs", "governance"],
    themes: [
      "neighbourhood first",
      "strategic autonomy",
      "diaspora diplomacy",
      "Indo-Pacific",
      "soft power through culture",
    ],
    essayTopics: [
      "India's civilizational soft power",
      "Non-alignment to multi-alignment",
      "Borders, connectivity, trust",
    ],
  }),
  exam({
    id: "ssc-descriptive",
    name: "SSC / descriptive English papers",
    shortName: "SSC Descriptive",
    aliases: ["ssc", "descriptive paper", "cgl descriptive"],
    country: "India",
    region: "India",
    continent: "Asia",
    kind: "essay-heavy",
    fields: ["current-affairs", "governance", "domestic", "society-culture"],
    themes: UPSC_SPEAK.slice(0, 20),
    essayTopics: [
      "Importance of discipline in student life",
      "Women empowerment in India",
      "Digital India — successes and gaps",
      "Environmental pollution",
      "Role of education in national development",
      "Unity in diversity",
      "Corruption — causes and remedies",
      "Social media — boon or bane",
      "Health is wealth",
      "India of my dreams",
    ],
  }),
  exam({
    id: "sat-essay-style",
    name: "College admissions essays (US style)",
    shortName: "US Admissions Essay",
    aliases: ["common app", "college essay", "personal statement", "sat essay"],
    country: "United States",
    region: "United States",
    continent: "North America",
    kind: "essay-heavy",
    fields: ["education", "abstract", "society-culture", "ethics"],
    themes: [
      "a challenge you reframed",
      "intellectual curiosity moment",
      "community you belong to",
      "a belief you revised",
    ],
    essayTopics: [
      "Tell a story only you can tell — about growth under pressure",
      "When did you change your mind about something important?",
      "Describe a community and your place in it",
      "What problem do you want university to help you tackle?",
    ],
  }),
  exam({
    id: "australian-public",
    name: "Australian Public Service interviews",
    shortName: "APS",
    aliases: ["aps", "australia public service"],
    country: "Australia",
    region: "Australia",
    continent: "Oceania",
    kind: "interview",
    fields: ["governance", "environment", "domestic", "ethics"],
    themes: [
      "public value",
      "indigenous partnership",
      "climate policy delivery",
      "frank and fearless advice",
    ],
    essayTopics: [
      "Integrity in public service",
      "Climate policy needs social licence",
    ],
  }),
  exam({
    id: "canada-ps",
    name: "Canada public service / FCS interviews",
    shortName: "Canada PS",
    aliases: ["canada public service", "foreign service canada"],
    country: "Canada",
    region: "Canada",
    continent: "North America",
    kind: "interview",
    fields: ["governance", "immigration", "international", "ethics"],
    themes: [
      "bilingual public service",
      "reconciliation in institutions",
      "immigration and identity",
    ],
    essayTopics: [
      "Diversity is a fact; inclusion is a practice",
      "Public trust is earned in quiet decisions",
    ],
  }),
];

export const EXAM_CATALOG: Exam[] = EXAMS;

export function getExamById(id: string | null | undefined): Exam | null {
  if (!id) return null;
  return EXAM_CATALOG.find((e) => e.id === id) ?? null;
}

export function searchExams(query: string): Exam[] {
  const q = query.trim().toLowerCase();
  if (!q) return EXAM_CATALOG;
  return EXAM_CATALOG.filter((e) => {
    const hay = [e.name, e.shortName, e.country, e.continent, e.kind, ...e.aliases]
      .join(" ")
      .toLowerCase();
    return hay.includes(q) || e.aliases.some((a) => a.includes(q) || q.includes(a));
  }).sort((a, b) => {
    const score = (e: Exam) =>
      e.shortName.toLowerCase() === q || e.aliases.some((x) => x === q)
        ? 0
        : e.shortName.toLowerCase().startsWith(q)
          ? 1
          : 2;
    return score(a) - score(b) || a.name.localeCompare(b.name);
  });
}

/** Combinatorial expansion staying inside exam-relevant material (>1L for major exams). */
export function estimateExamTopicSpace(exam: Exam, mode: "speak" | "essay" = "speak"): number {
  if (mode === "essay") {
    // curated titles × light situational frames × field lenses
    return exam.essayTopics.length * 48 * 36 * Math.max(1, exam.fields.length);
  }
  return exam.themes.length * 80 * 40 * 36;
}
