/** Expanded topic fields / domains users can filter on. */

export const CATEGORIES = [
  "all",
  "international",
  "domestic",
  "finance",
  "nutrition",
  "current-affairs",
  "governance",
  "economy",
  "science-tech",
  "technology-ai",
  "environment",
  "climate",
  "energy",
  "education",
  "society-culture",
  "ethics",
  "health",
  "sports",
  "abstract",
  "business",
  "law-justice",
  "media",
  "agriculture",
  "security-defence",
  "urban-planning",
  "psychology",
  "gender-equity",
  "immigration",
  "infrastructure",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const SUBJECTS: Record<Exclude<Category, "all">, string[]> = {
  international: [
    "UN Security Council reform",
    "trade wars",
    "climate finance pledges",
    "refugee quotas",
    "soft power through culture",
    "sanctions effectiveness",
    "diplomatic asylum",
    "Indo-Pacific strategy",
    "BRICS expansion",
    "WTO dispute settlement",
    "foreign aid conditionality",
    "passport privilege",
    "arms control treaties",
    "cross-border river disputes",
    "extradition ethics",
    "global tax minimums",
    "digital sovereignty",
    "pandemic treaty politics",
    "peacekeeping mandates",
    "maritime exclusive zones",
    "Olympic boycotts",
    "cultural diplomacy",
    "diaspora voting rights",
    "global south debt relief",
    "space resource claims",
  ],
  domestic: [
    "federal-state conflicts",
    "urban versus rural budgets",
    "national language policy",
    "internal migration",
    "reservation debates",
    "local body elections",
    "farm protest lessons",
    "city policing models",
    "public distribution systems",
    "citizen identity cards",
    "national holidays meaning",
    "census controversies",
    "domestic tourism push",
    "inter-state water sharing",
    "capital city relocation",
    "homegrown startup champions",
    "vernacular media power",
    "school mid-day meals",
    "domestic fuel pricing",
    "heritage conservation locally",
    "community policing",
    "municipal garbage contracts",
    "state scholarship design",
    "domestic violence shelters",
    "national sports academies",
  ],
  finance: [
    "inflation targeting",
    "central bank digital currency",
    "stock market circuit breakers",
    "credit card debt culture",
    "financial literacy gaps",
    "crypto taxation",
    "sovereign wealth funds",
    "microfinance interest rates",
    "insurance for the poor",
    "pension adequacy",
    "fintech inclusion",
    "shadow banking",
    "green bonds integrity",
    "capital gains tax design",
    "remittance fees",
    "SME loan collateral",
    "wealth inequality metrics",
    "bank merger consumer impact",
    "payment app monopolies",
    "real estate speculation",
    "gold as household savings",
    "budget deficit politics",
    "subsidy leakage",
    "crowd funding regulation",
    "personal bankruptcy stigma",
  ],
  nutrition: [
    "ultra-processed foods",
    "school meal nutrition",
    "sugar taxes",
    "protein myths",
    "micronutrient deficiency",
    "fasting trends",
    "vegan diets in schools",
    "food deserts",
    "supplement advertising",
    "breastfeeding support policy",
    "obesity stigma",
    "sports nutrition hype",
    "labeling front-of-pack",
    "traditional diets revival",
    "GM food acceptance",
    "salt reduction campaigns",
    "hospital food quality",
    "nutrition in pregnancy",
    "child anemia programs",
    "influencer diet advice",
    "fortified foods",
    "hunger versus obesity paradox",
    "meat alternatives",
    "community kitchens",
    "nutrition education in curricula",
  ],
  "current-affairs": [
    "election misinformation",
    "AI regulation headlines",
    "energy price shocks",
    "student protests",
    "climate litigation wins",
    "celebrity political endorsements",
    "platform content bans",
    "vaccine policy updates",
    "mega sporting event host bids",
    "rare earth supply chokes",
    "campus speech codes",
    "gig worker strike waves",
    "border flashpoints",
    "tourism overcrowding taxes",
    "water crisis summers",
    "deepfake scandals",
    "housing unaffordability spikes",
    "public transport fare hikes",
    "museum artifact returns",
    "space launch nationalism",
    "heatwave emergency responses",
    "cryptocurrency crackdowns",
    "influencer tax raids",
    "education board exam leaks",
    "diplomatic summit outcomes",
  ],
  governance: [
    "parliamentary reform",
    "judicial independence",
    "lobbying transparency",
    "civil service neutrality",
    "right to information",
    "anti-corruption ombudsmen",
    "emergency powers",
    "electoral funding",
    "federalism bargains",
    "citizen assemblies",
    "regulatory sandboxes",
    "public consultation design",
    "whistleblower protection",
    "police accountability",
    "bureaucracy digitization",
    "term limits",
    "proportional representation",
    "official secrets balance",
    "local government funding",
    "ethics commissions",
    "open data mandates",
    "appointment transparency",
    "performance budgeting",
    "sunset clauses for laws",
    "participatory budgeting",
  ],
  economy: [
    "universal basic income pilots",
    "minimum wage indexing",
    "industrial policy",
    "informal economy formalization",
    "manufacturing reshoring",
    "tourism-led growth risks",
    "startup ecosystem depth",
    "brain drain incentives",
    "trade liberalization",
    "carbon border adjustments",
    "platform monopolies",
    "housing affordability",
    "agriculture market reforms",
    "public-private partnerships",
    "youth unemployment traps",
    "care economy valuation",
    "export dependency",
    "commodity price swings",
    "middle-income trap",
    "skill mismatch",
    "automation and jobs",
    "regional inequality",
    "black economy",
    "consumer demand shocks",
    "innovation clusters",
  ],
  "science-tech": [
    "gene editing for disease",
    "quantum readiness",
    "nuclear fusion timelines",
    "lab-grown meat labeling",
    "space debris cleanup",
    "open scientific data",
    "robotics in eldercare",
    "brain-computer interfaces",
    "antibiotic discovery crisis",
    "satellite internet access",
    "wearable health privacy",
    "synthetic biology patents",
    "STEM gender gaps",
    "citizen science",
    "research funding bias",
    "clinical trial diversity",
    "science communication trust",
    "telescope megaprojects",
    "vaccine platform tech",
    "drone delivery corridors",
    "materials for climate",
    "ocean mapping race",
    "precision agriculture sensors",
    "science olympiad pressure",
    "lab safety culture",
  ],
  "technology-ai": [
    "large language models in schools",
    "algorithmic hiring bias",
    "AI in courts",
    "deepfake elections",
    "autonomous vehicles liability",
    "facial recognition bans",
    "AI art authorship",
    "chatbot therapy risks",
    "content moderation labor",
    "open-source AI safety",
    "compute nationalism",
    "prompt injection threats",
    "AI watermarking",
    "automation of journalism",
    "recommendation rabbit holes",
    "data center energy hunger",
    "AI tutors equity",
    "robot taxation ideas",
    "synthetic media labeling",
    "model hallucination harms",
    "AI for climate modeling",
    "surveillance capitalism 2.0",
    "human-in-the-loop design",
    "AI military targeting ethics",
    "right to explanation",
  ],
  environment: [
    "plastic packaging bans",
    "urban biodiversity",
    "ocean cleanup claims",
    "deforestation offsets",
    "wildlife corridors",
    "air quality standards",
    "wetland protection",
    "invasive species control",
    "e-waste recycling",
    "circular economy mandates",
    "pesticide runoff",
    "noise pollution cities",
    "soil degradation",
    "mangrove restoration",
    "greenwashing penalties",
    "community forest rights",
    "glacier melt local impact",
    "single-use culture",
    "composting infrastructure",
    "eco-tourism ethics",
    "mining near sanctuaries",
    "river rejuvenation theater",
    "bee population decline",
    "desertification control",
    "plastic credit markets",
  ],
  climate: [
    "net-zero timelines",
    "loss and damage funds",
    "heatwave early warnings",
    "climate migration",
    "carbon markets integrity",
    "methane from livestock",
    "coastal retreat planning",
    "youth climate litigation",
    "adaptation versus mitigation",
    "fossil fuel phaseouts",
    "climate education mandates",
    "insurance retreat from coasts",
    "urban heat islands",
    "permafrost thaw risks",
    "agriculture emission cuts",
    "just transition for miners",
    "climate clubs of nations",
    "geoengineering temptation",
    "corporate net-zero pledges",
    "climate doomism",
    "school strike impact",
    "disaster resilience budgets",
    "indigenous climate knowledge",
    "food system emissions",
    "aviation shame debates",
  ],
  energy: [
    "coal phase-out pace",
    "nuclear versus renewables",
    "green hydrogen bets",
    "grid storage gaps",
    "rooftop solar equity",
    "EV subsidy design",
    "oil price political risk",
    "hydropower displacement",
    "biogas for villages",
    "energy poverty",
    "transmission line conflicts",
    "battery mineral ethics",
    "peak demand management",
    "offshore wind backlash",
    "diesel generator dependence",
    "energy efficiency first",
    "smart meter privacy",
    "fuel price targeting",
    "just energy transition",
    "gas as bridge fuel myth",
    "community energy co-ops",
    "nuclear waste siting",
    "data center power deals",
    "cookstove transitions",
    "strategic petroleum reserves",
  ],
  education: [
    "standardized testing culture",
    "mother-tongue instruction",
    "phone bans in class",
    "teacher pay retention",
    "vocational prestige",
    "homework load",
    "AI writing detectors",
    "campus free speech",
    "tuition freezes",
    "inclusive classrooms",
    "exam malpractice",
    "boarding school mental health",
    "curriculum culture wars",
    "sports scholarships ethics",
    "online degree recognition",
    "adult literacy drives",
    "special education funding",
    "coding in primary school",
    "university ranking obsession",
    "gap years value",
    "corporal punishment bans",
    "critical thinking drills",
    "homeschooling regulation",
    "international student quotas",
    "library future",
  ],
  "society-culture": [
    "arranged marriage norms",
    "language extinction",
    "canceled culture",
    "celebrity activism",
    "heritage tourism",
    "festival noise rules",
    "beauty standards media",
    "filial piety today",
    "street art legality",
    "food appropriation debates",
    "museum repatriation",
    "esports as culture",
    "interfaith dialogue",
    "nightlife policy",
    "comic censorship",
    "ancestry DNA privacy",
    "folk arts survival",
    "national service ideas",
    "multigenerational homes",
    "dating app culture",
    "tipping etiquette shifts",
    "reading decline",
    "public mourning rituals",
    "community radio",
    "costume and identity",
  ],
  ethics: [
    "lying for greater good",
    "animal testing necessity",
    "wealth inheritance morality",
    "end-of-life autonomy",
    "whistleblowing loyalty",
    "just war today",
    "surveillance for safety",
    "effective altruism critiques",
    "parental genetic selection",
    "AI moral patienthood",
    "forgiveness after atrocity",
    "civil disobedience",
    "punishment versus rehab",
    "organ opt-out systems",
    "academic integrity AI age",
    "cultural relativism limits",
    "promise-keeping in politics",
    "duty to vote",
    "ethical consumption limits",
    "soldier moral injury",
    "sharing passwords ethics",
    "truth-telling to children",
    "corporate social responsibility",
    "humanitarian intervention",
    "privacy versus transparency",
  ],
  health: [
    "universal healthcare models",
    "mental health sick leave",
    "antibiotic resistance",
    "telemedicine expansion",
    "hospital staffing shortages",
    "opioid rules",
    "maternal mortality gaps",
    "vaccine mandates travel",
    "rural hospital closures",
    "lonely aging",
    "screen time toddlers",
    "addiction as disease",
    "period poverty",
    "sleep deprivation epidemic",
    "alternative medicine regulation",
    "blood donation incentives",
    "gene therapy pricing",
    "workplace wellness theater",
    "sports concussion protocols",
    "cosmetic surgery ads",
    "pandemic border closures",
    "primary care neglect",
    "health misinformation",
    "caregiver burnout",
    "pharmacy deserts",
  ],
  sports: [
    "athlete political protests",
    "pay equality in sport",
    "youth specialization pressure",
    "mega event hosting costs",
    "VAR fairness",
    "doping culture",
    "esports unions",
    "national team selection bias",
    "sports betting ads",
    "disability sports funding",
    "coach abuse scandals",
    "club versus country",
    "body image in gymnastics",
    "fan violence laws",
    "women's league investment",
    "school PE cuts",
    "climate impact of stadiums",
    "transfer fee inflation",
    "sports diplomacy",
    "medal obsession",
    "community facilities access",
    "referee accountability",
    "age fraud scandals",
    "traditional sports revival",
    "athlete mental health",
  ],
  abstract: [
    "progress",
    "silence",
    "ambition",
    "courage",
    "failure",
    "curiosity",
    "perfectionism",
    "loneliness",
    "home",
    "optimism",
    "discipline",
    "memory",
    "chance",
    "beauty",
    "waiting",
    "simplicity",
    "authority",
    "loyalty",
    "innovation",
    "tradition",
    "freedom",
    "responsibility",
    "hope",
    "change",
    "truth",
  ],
  business: [
    "founder mode leadership",
    "four-day work weeks",
    "layoffs and culture",
    "brand activism risks",
    "supply chain ethics",
    "influencer disclosure",
    "subscription fatigue",
    "unicorn valuations",
    "office return mandates",
    "diversity hiring targets",
    "crisis PR",
    "family business succession",
    "unpaid internships",
    "board diversity",
    "customer data monetization",
    "exit interview honesty",
    "greenwashing brands",
    "service AI bots",
    "price discrimination online",
    "venture capital power",
    "middle manager value",
    "franchise expansion",
    "product bundling ethics",
    "remote-first culture",
    "creator economy rights",
  ],
  "law-justice": [
    "bail reform",
    "free speech limits",
    "privacy rights",
    "hate speech thresholds",
    "judicial delays",
    "police custody deaths",
    "plea bargaining",
    "death penalty debates",
    "defamation laws",
    "intellectual property AI",
    "environmental courts",
    "anti-trust against tech",
    "consumer class actions",
    "legal aid gaps",
    "tribunals proliferation",
    "contempt of court",
    "media trials",
    "witness protection",
    "juvenile justice",
    "cybercrime evidence",
    "contract fairness",
    "property rights women",
    "labor code flexibility",
    "electoral law integrity",
    "access to justice",
  ],
  media: [
    "fake news ecosystems",
    "newsroom layoffs",
    "paywalled truth",
    "influencer journalism",
    "public broadcasting funding",
    "press freedom rankings",
    "clickbait incentives",
    "war reporting ethics",
    "op-ed independence",
    "local news deserts",
    "algorithmic amplification",
    "media ownership concentration",
    "fact-check fatigue",
    "podcast politics",
    "citizen journalism risks",
    "advertising versus editorial",
    "deepfake newsrooms",
    "sports rights TV prices",
    "cinema censorship boards",
    "streaming cultural power",
    "press accreditation fights",
    "anonymous sources use",
    "hate in comment sections",
    "journalist safety",
    "media literacy curricula",
  ],
  agriculture: [
    "MSP debates",
    "farmer suicides policy",
    "climate-smart agriculture",
    "seed sovereignty",
    "pesticide regulation",
    "farm loan waivers",
    "agri-tech startups",
    "cold chain gaps",
    "livestock methane",
    "land fragmentation",
    "contract farming risks",
    "organic certification access",
    "water-intensive crops",
    "farmer producer orgs",
    "rural warehouse receipts",
    "soil carbon credits",
    "crop insurance design",
    "urban farming",
    "fisheries overcatch",
    "food processing jobs",
    "dairy cooperatives",
    "monoculture risks",
    "women in farm labor",
    "agrarian protests tactics",
    "export bans on food",
  ],
  "security-defence": [
    "border infrastructure",
    "cyber defence doctrine",
    "terrorism financing",
    "intelligence oversight",
    "defence indigenization",
    "civil-military relations",
    "drone warfare ethics",
    "coastal security",
    "critical infrastructure protection",
    "radicalization online",
    "peacekeeping contributions",
    "nuclear deterrence debates",
    "military conscription",
    "veteran welfare",
    "hybrid warfare",
    "space force roles",
    "police versus military tasks",
    "disaster force deployment",
    "arms export ethics",
    "alliance commitments",
    "insurgency amnesty",
    "surveillance of citizens",
    "recruitment shortfalls",
    "women in combat roles",
    "information warfare",
  ],
  "urban-planning": [
    "affordable housing mandates",
    "transit-oriented development",
    "slum upgrading dignity",
    "street vendor rights",
    "congestion pricing",
    "public toilets access",
    "urban flooding drains",
    "heritage versus density",
    "night-time economy zones",
    "green cover targets",
    "parking minimum reforms",
    "informal settlements tenure",
    "smart city outcomes",
    "walkability equity",
    "mixed-use neighborhoods",
    "waste-to-energy plants",
    "urban heat shelters",
    "rental housing regulation",
    "bike lane backlash",
    "waterfront privatization",
    "migrant worker hostels",
    "city data dashboards",
    "fencing public parks",
    "skyscraper ego projects",
    "neighborhood noise maps",
  ],
  psychology: [
    "attention economy harms",
    "impostor syndrome",
    "social media envy",
    "burnout culture",
    "grief literacy",
    "habit formation myths",
    "cognitive bias in voting",
    "therapy stigma",
    "childhood trauma discourse",
    "resilience training hype",
    "loneliness epidemic",
    "dopamine detox fad",
    "perfectionism in students",
    "groupthink at work",
    "moral licensing",
    "fear of public speaking",
    "decision fatigue",
    "identity and labels",
    "compassion fatigue",
    "mindfulness commercialization",
    "sleep and mood",
    "anger in politics",
    "peer pressure online",
    "memory and misinformation",
    "self-help industry ethics",
  ],
  "gender-equity": [
    "pay gap persistence",
    "care work unpaid",
    "women in STEM",
    "political reservation",
    "period leave debates",
    "safety in public transport",
    "sports pay equality",
    "gender-neutral parenting",
    "workplace harassment processes",
    "maternity and paternity norms",
    "beauty labor expectations",
    "trans rights in sport",
    "women farmers recognition",
    "financial inclusion women",
    "girls' education barriers",
    "domestic work visas",
    "representation in film",
    "men's mental health silence",
    "inheritance laws bias",
    "online gender abuse",
    "STEM toy marketing",
    "boardroom tokenism",
    "reproductive rights access",
    "uniform policy dignity",
    "gender data gaps",
  ],
  immigration: [
    "skilled visa lotteries",
    "asylum backlogs",
    "border wall politics",
    "sanctuary cities",
    "guest worker programs",
    "citizenship tests",
    "language requirements",
    "refugee integration jobs",
    "brain drain ethics",
    "diaspora remittances",
    "illegal migration push factors",
    "detention conditions",
    "family reunification rules",
    "climate refugees status",
    "employer sponsorship power",
    "anti-immigrant populism",
    "passport ranking inequality",
    "student visa churn",
    "amnesty debates",
    "multiculturalism models",
    "border tech surveillance",
    "human trafficking routes",
    "return migration incentives",
    "local housing pressure narratives",
    "immigrant entrepreneurship",
  ],
  infrastructure: [
    "high-speed rail tradeoffs",
    "bridge safety accountability",
    "airport expansion protests",
    "port privatization",
    "broadband as utility",
    "metros versus buses",
    "toll road fairness",
    "power blackout resilience",
    "water pipeline leakage",
    "wastewater reuse",
    "logistics corridors",
    "last-mile connectivity",
    "PPP delayed projects",
    "maintenance over megaprojects",
    "disaster-proof schools",
    "electric bus fleets",
    "freight rail revival",
    "smart grid upgrades",
    "public housing construction pace",
    "stadium white elephants",
    "digital public infrastructure",
    "rural road quality",
    "canal modernization",
    "cable and street clutter",
    "infrastructure corruption risks",
  ],
};

export function categoryLabel(category: Category): string {
  if (category === "all") return "All fields";
  return category
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}
